Repository Flow-Launcher/flow-launcher.github.io, pull requests merged in 2025-03, with the labels that each got.

#50 Add plugin.md
  src/data/plugins/link-opener/images/MultiSearchWithArgs.png
  src/data/plugins/link-opener/images/MultiSearchWithArgsSettings.png
  src/data/plugins/link-opener/images/SearchWithArgs.png
  src/data/plugins/link-opener/images/SearchWithArgsSettings.png
  src/data/plugins/link-opener/images/SearchWithoutArgs.png
  src/data/plugins/link-opener/images/SearchWithoutArgsSettings.png
  src/data/plugins/link-opener/plugin.md
Labels: plugin submission

#51 fix: correct winget installation command syntax
  src/components/DownloadDIalog.astro
Labels: bug

#53 update README with forking and editing instructions
  README.md
Labels: documentation

#52 fix schema files being unavailable due to not being in /public directory
  public/schemas/plugin.schema.json
  public/schemas/settings-template.schema.json
Labels: bug

#56 feat: add support for using mdx files for plugin descriptions
  astro.config.mjs
  package-lock.json
  package.json
  src/content.config.ts
  src/pages/plugins/[slug]/index.astro
Labels: enhancement

#57 fix: update fetch URL for plugins JSON to use raw GitHub content
  src/getPluginsJson.ts
Labels: bug
